#!/usr/bin/env bash

echo 'red ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# Install tini
TINI_VERSION="v0.18.0"
curl -Ls https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini -o /opt/docker/bin/tini
chmod +x /opt/docker/bin/tini

# Create lucky group
groupadd -g 32766 redone


